Added error simulation to Job-1 and conditional execution for Job-2 and Job-2-Not-Run based on Job-1's success or failure

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -17,10 +17,13 @@ jobs:
       - name: List files in the repository
         run: |
           ls ${{ github.workspace }}
+      - name: Simulate error
+        run: exit 1
       - run: echo "🍏 This job's status is ${{ job.status }}."
   Job-2:
     runs-on: ubuntu-latest
     needs: Job-1
+    if: ${{ success() }}
     steps:
       - name: Echo job name
         run: echo "The current job's name is ${{ github.job }}"
@@ -36,3 +39,12 @@ jobs:
         run: |
           ls ${{ github.workspace }}
       - run: echo "🍏 This job's status is ${{ job.status }}."
+
+  Job-2-Not-Run:
+    runs-on: ubuntu-latest
+    needs: Job-1
+    if: ${{ failure() }}
+    steps:
+      - name: Echo job name
+        run: echo "The current job's name is ${{ github.job }}"
+      - run: echo "🚫 Job-2 was not run because Job-1 failed."
